CREATE DATABASE PROG3FINAL
USE PROG3FINAL

CREATE TABLE USUARIOS
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
USERNAME VARCHAR(MAX),
PASS VARCHAR(MAX)
);

INSERT INTO USUARIOS VALUES('Admin','123456');

CREATE TABLE VEHICULOS
(
    ID INT NOT NULL IDENTITY,
    MARCA VARCHAR(100),
    MODELO VARCHAR(100) PRIMARY KEY,
    ANIO INT,
    COLOR VARCHAR(100),
    PRECIO_DIA INT,
    TIPO VARCHAR(100),
    CAPACIDAD_CARGA INT,
    PASAJEROS INT,
    MATRICULA VARCHAR(100),
    NO_SEGURO VARCHAR(100),
    FOTO VARCHAR(MAX),
    LATITUD VARCHAR(100),
    LONGITUD VARCHAR(100),
	RESERVADO VARCHAR(100)
);


SELECT * FROM VEHICULOS;
UPDATE VEHICULOS SET RESERVADO = 'NO'

CREATE TABLE CLIENTES
(
  ID INT NOT NULL IDENTITY,
  CEDULA VARCHAR(100),
  NOMBRE VARCHAR(100) PRIMARY KEY,
  CORREO VARCHAR(100),
  LICENCIA VARCHAR(100),
  NACIONALIDAD VARCHAR(100),
  TIPO_SANGRE VARCHAR(100),
  FOTO VARCHAR(MAX),
  FOTO_LICENCIA VARCHAR(MAX)
);

DROP TABLE CLIENTES 

INSERT INTO CLIENTES VALUES('Admin','Admin','Admin','Admin','Admin','Admin','Admin','Admin','Admin');

SELECT * FROM CLIENTES;

CREATE TABLE RESERVAS ( 
ID INT NOT NULL PRIMARY KEY IDENTITY,
VEHICULO VARCHAR(100) REFERENCES VEHICULOS(MODELO), 
CLIENTE VARCHAR(100) REFERENCES CLIENTES(NOMBRE), 
FECHA_INICIO VARCHAR(100), 
FECHA_FIN VARCHAR(100), 
MONTO INT 
);

INSERT INTO RESERVAS VALUES('Civic','Noe Eduardo Medina Henriquez',GETDATE(),'2021-04-30',0);
DELETE FROM RESERVAS
SELECT * FROM RESERVAS

/* TRIGGER QUE CAMBIA ESTADO DEL VEHICULO */

CREATE TRIGGER RESERVANDO ON RESERVAS
FOR INSERT
AS
DECLARE @MARCA VARCHAR(100)
DECLARE @ID INT

SELECT @ID = V.ID FROM RESERVAS V

SELECT @MARCA = VH.MARCA FROM VEHICULOS VH
JOIN RESERVAS R ON (VH.MARCA = R.VEHICULO)
WHERE VH.MARCA = @MARCA

UPDATE VEHICULOS SET RESERVADO = 'SI'
FROM VEHICULOS,RESERVAS
WHERE VEHICULOS.MODELO = RESERVAS.VEHICULO AND RESERVAS.ID = @ID 

PRINT 'SE EJECUTO TRIGGER'
GO


DROP TRIGGER RESERVANDO


/* TRIGGER QUE ASIGNA MONTO A RESERVA */

CREATE TRIGGER ASIGNAR_MONTO ON RESERVAS
FOR INSERT
AS

DECLARE @PRECIO INT
DECLARE @CANTIDAD_DIAS INT
DECLARE @ID INT

SELECT @ID = R.ID FROM RESERVAS R

SELECT @PRECIO = V.PRECIO_DIA FROM VEHICULOS V
JOIN RESERVAS R ON (V.MODELO = R.VEHICULO)
WHERE V.MODELO = R.VEHICULO

SELECT @CANTIDAD_DIAS = DATEDIFF(DAY,R.FECHA_INICIO,R.FECHA_FIN)
FROM RESERVAS R

UPDATE RESERVAS SET MONTO = @PRECIO * @CANTIDAD_DIAS
FROM RESERVAS,VEHICULOS
WHERE VEHICULOS.MODELO = RESERVAS.VEHICULO AND RESERVAS.ID = @ID

PRINT 'SE EJECUTO EL SEGUNDO'
GO

DROP TRIGGER ASIGNAR_MONTO 


/* TRIGGER PARA HABILITAR VEHICULO CUANDO EL MONTO SEA 0 */

CREATE TRIGGER HABILITAR ON RESERVAS
AFTER UPDATE
AS
DECLARE @MONTO VARCHAR(100)
DECLARE @ID INT

SELECT @ID = R.ID FROM RESERVAS R
SELECT @MONTO = R.MONTO FROM RESERVAS R

IF @MONTO <= 0
	BEGIN
		UPDATE VEHICULOS SET RESERVADO = 'NO'
		FROM VEHICULOS,RESERVAS
		WHERE VEHICULOS.MODELO = RESERVAS.VEHICULO
		AND RESERVAS.ID = @ID

		PRINT 'SE DESHABILITO'
END

DROP TRIGGER HABILITAR

UPDATE RESERVAS SET MONTO = 0 WHERE ID = 22

SELECT * FROM RESERVAS;
SELECT * FROM VEHICULOS;

UPDATE RESERVAS SET MONTO = 0 where id = 15;
INSERT INTO RESERVAS VALUES('Civic','Noe Eduardo Medina Henriquez',GETDATE(),'2021-04-30',0);
DELETE FROM RESERVAS

/*
Listado de beneficios por vehículos. Va a mostrar un listado de todos los vehículos,
la cantidad de veces que se han reservado cada uno,
y la cantidad de dinero que se ha facturado gracias a ese vehículo.


Clientes que deben. Aparecerá un listado de los clientes que deben, cedula, nombre, apellido y monto.

*/

DECLARE @FECHA1 DATE
DECLARE @FECHA2 DATE

SELECT @FECHA1 = R.FECHA_INICIO FROM RESERVAS R
SELECT @FECHA2 = R.FECHA_FIN FROM RESERVAS R

SELECT * FROM RESERVAS R
JOIN VEHICULOS V ON (V.MODELO = R.VEHICULO)
WHERE R.FECHA_INICIO = GETDATE() 

SELECT * FROM vehiculos
SELECT * FROM RESERVAS

SELECT V.MARCA AS 'MARCA VEHICULO',V.MODELO AS 'MODELO VEHICULO',
V.COLOR AS 'COLOR VEHICULO', COUNT(V.MODELO) AS 'CANTIDAD DE VECES ALQUILADO',R.MONTO
FROM RESERVASBACKUP R
JOIN VEHICULOS V ON (V.MODELO = R.VEHICULO)
GROUP BY R.VEHICULO,V.MARCA,V.COLOR,R.MONTO,V.MODELO 
HAVING COUNT(V.MODELO) >= 1

SELECT C.CEDULA,C.NOMBRE,R.MONTO FROM CLIENTES C JOIN RESERVAS R ON (R.CLIENTE = C.NOMBRE) WHERE R.MONTO > 0


CREATE TABLE RESERVASBACKUP ( 
ID INT NOT NULL PRIMARY KEY IDENTITY,
VEHICULO VARCHAR(100) REFERENCES VEHICULOS(MODELO), 
CLIENTE VARCHAR(100) REFERENCES CLIENTES(NOMBRE), 
FECHA_INICIO VARCHAR(100), 
FECHA_FIN VARCHAR(100), 
MONTO INT 
);


CREATE TRIGGER HISTORICO ON RESERVAS
FOR INSERT
AS

DECLARE @PRECIO INT
DECLARE @CANTIDAD_DIAS INT
DECLARE @ID INT
DECLARE @VEHICULO VARCHAR(100)
DECLARE @CLIENTE VARCHAR(100)
DECLARE @FECHA_INICIO VARCHAR(100)
DECLARE @FECHA_FIN VARCHAR(100)
DECLARE @MONTO INT

SELECT @PRECIO = V.PRECIO_DIA FROM VEHICULOS V
JOIN RESERVAS R ON (V.MODELO = R.VEHICULO)
WHERE V.MODELO = R.VEHICULO

SELECT @CANTIDAD_DIAS = DATEDIFF(DAY,R.FECHA_INICIO,R.FECHA_FIN)
FROM RESERVAS R

SELECT @VEHICULO = I.VEHICULO FROM INSERTED I;
SELECT @CLIENTE = I.CLIENTE FROM INSERTED I;
SELECT @FECHA_INICIO = I.FECHA_INICIO FROM INSERTED I;
SELECT @FECHA_FIN = I.FECHA_FIN FROM INSERTED I;
SELECT @MONTO = @PRECIO * @CANTIDAD_DIAS

INSERT INTO RESERVASBACKUP VALUES(@VEHICULO,@CLIENTE,@FECHA_INICIO,@FECHA_FIN,@MONTO);

UPDATE RESERVASBACKUP SET MONTO = @PRECIO * @CANTIDAD_DIAS
FROM RESERVASBACKUP,VEHICULOS
WHERE VEHICULOS.MODELO = RESERVASBACKUP.VEHICULO AND RESERVASBACKUP.ID = @ID

PRINT 'HOLA'
GO

DROP TRIGGER HISTORICO


/* CONSULTA PARA DETERMINAR LAS FECHAS EN LAS QUE NO ESTA DISPONIBLE EL VEHICULO */

SELECT V.MODELO AS 'MODELO', R.FECHA_INICIAL AS 'FECHA INICIO',
R.FECHA_FIN AS 'FECHA FINAL'
FROM VEHICULOS V
JOIN RESERVAS R ON (V.MODELO = R.VEHICULO)


SELECT V.MODELO,V.COLOR,V.ANIO,R.FECHA_INICIO,FECHA_FIN FROM VEHICULOS V 
JOIN RESERVAS R ON (V.MODELO = R.VEHICULO) WHERE R.FECHA_INICIO NOT IN('2021-04-20') AND R.FECHA_FIN NOT IN('2021-04-31')


SELECT * FROM VEHICULOS V JOIN RESERVAS R ON (V.MODELO = R.VEHICULO) WHERE R.FECHA_INICIO >= '2021-04-24' OR R.FECHA_FIN <= '2021-04-30'

SELECT V.MARCA,V.MODELO,V.ANIO,V.COLOR,V.PRECIO_DIA FROM VEHICULOS V JOIN RESERVAS R ON (V.MODELO = R.VEHICULO) 
WHERE R.FECHA_INICIO NOT BETWEEN '2021-05-20' AND '2021-05-30' 
AND R.FECHA_FIN NOT BETWEEN '2021-05-20' AND '2021-05-30' OR V.RESERVADO = 'NO'
GROUP BY V.MARCA,V.MODELO,V.ANIO,V.COLOR,V.PRECIO_DIA
HAVING COUNT(R.VEHICULO) >= 1

SELECT * FROM VEHICULOS V JOIN RESERVAS R ON (V.MODELO = R.VEHICULO) WHERE R.FECHA_INICIO NOT IN ('2021-05-01')
AND R.FECHA_INICIO NOT IN ('2021-05-30') AND R.FECHA_FIN NOT IN('2021-05-01') AND R.FECHA_FIN NOT IN('2021-05-30')


SELECT * FROM RESERVAS R WHERE R.VEHICULO = 'D-MAX' 
AND ('2021-04-26' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN OR '2021-04-30' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN)

SELECT * FROM RESERVAS

SELECT TOP 1
IF(SELECT * FROM RESERVAS R WHERE R.VEHICULO = 'D-MAX' 
AND ('2021-04-26' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN OR '2021-04-30' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN);


SELECT ISNULL((SELECT * FROM RESERVAS R WHERE R.VEHICULO = 'D-MAX' 
AND ('2021-04-26' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN OR '2021-04-30' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN)),0)

SELECT 
CASE VEHICULO
    WHEN 'Civic' 
    THEN 1
    ELSE 0
    END
    AS Existe
FROM
    RESERVAS R 
WHERE
	 R.VEHICULO = 'Civic' 
	AND ('2021-04-26' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN OR '2021-04-30' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN)


SELECT R.VEHICULO,
		CASE WHEN R.VEHICULO = 'D-MAX'
		AND ('2021-04-24' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN OR '2021-04-30' BETWEEN R.FECHA_INICIO AND R.FECHA_FIN)
		THEN 'NO'
		ELSE 'SI' 
		END
		AS DISPONIBLE
		FROM RESERVAS R


		SELECT * FROM VEHICULOS
		SELECT * FROM CLIENTES
		select * from reservas

